base_url = "https://j-h-a-r-c-h-i-v-e.com"
title = "J-H"
default_language = "en"
build_search_index = true
generate_feeds = false
ignored_content = ["content/shop/**"]


[markdown]
hard_breaks = false
bottom_footnotes = true

[languages]
[languages.kr]
title = "제이대시에이치"